"""Auto migration

Revision ID: 23d69c07a5a0
Revises: abc123def456
Create Date: 2025-12-04 15:09:01.044185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23d69c07a5a0'
down_revision: Union[str, Sequence[str], None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_messages', 'direction',
               existing_type=postgresql.ENUM('USER_TO_ADMIN', 'ADMIN_TO_USER', name='messagedirection'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('user_messages', 'status',
               existing_type=postgresql.ENUM('SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_messages', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'),
               existing_nullable=True)
    op.alter_column('user_messages', 'direction',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('USER_TO_ADMIN', 'ADMIN_TO_USER', name='messagedirection'),
               existing_nullable=False)
    # ### end Alembic commands ###
