"""add_file_fields_to_broadcasts

Revision ID: 4071dfa9e07e
Revises: 9ac6d067ec40
Create Date: 2026-01-14 19:05:58.340520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4071dfa9e07e'
down_revision: Union[str, Sequence[str], None] = '9ac6d067ec40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('file_url', sa.String(length=500), nullable=True))
    op.add_column('broadcasts', sa.Column('file_name', sa.String(length=200), nullable=True))
    op.add_column('broadcasts', sa.Column('photos_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'photos_json')
    op.drop_column('broadcasts', 'file_name')
    op.drop_column('broadcasts', 'file_url')
    # ### end Alembic commands ###
