"""add_bot_users_table

Revision ID: b5b529f3b7d3
Revises: 23d69c07a5a0
Create Date: 2025-12-17 20:27:30.456443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b529f3b7d3'
down_revision: Union[str, Sequence[str], None] = '23d69c07a5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_utm_source', sa.String(length=100), nullable=True),
    sa.Column('last_segment', sa.String(length=50), nullable=True),
    sa.Column('has_contact', sa.Boolean(), nullable=True),
    sa.Column('has_lead', sa.Boolean(), nullable=True),
    sa.Column('is_subscriber', sa.Boolean(), nullable=True),
    sa.Column('has_chatted_with_admin', sa.Boolean(), nullable=True),
    sa.Column('unread_admin_messages', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('contact_shared_at', sa.DateTime(), nullable=True),
    sa.Column('lead_created_at', sa.DateTime(), nullable=True),
    sa.Column('last_user_path', sa.JSON(), nullable=True),
    sa.Column('user_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_bot_users_id'), 'bot_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_users_id'), table_name='bot_users')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
