"""Add user_messages table

Revision ID: abc123def456
Revises: 3d5fe92a626a
Create Date: 2025-01-15 10:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'abc123def456'
down_revision: Union[str, None] = '3d5fe92a626a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('admin_id', sa.BigInteger(), nullable=True),
        sa.Column('message_text', sa.Text(), nullable=True),
        sa.Column('photo_url', sa.String(length=500), nullable=True),
        sa.Column('document_url', sa.String(length=500), nullable=True),
        sa.Column('direction', sa.Enum('USER_TO_ADMIN', 'ADMIN_TO_USER', name='messagedirection'), nullable=False),
        sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='messagestatus'), nullable=True),
        sa.Column('lead_id', sa.Integer(), nullable=True),
        sa.Column('utm_source', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(), nullable=True),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_messages_id'), 'user_messages', ['id'], unique=False)
    op.create_index(op.f('ix_user_messages_user_id'), 'user_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_messages_user_id'), table_name='user_messages')
    op.drop_index(op.f('ix_user_messages_id'), table_name='user_messages')
    op.drop_table('user_messages')
    # ### end Alembic commands ###